name: 功能请求 (Feature Request)
description: 为 CloudRank 插件提出新功能或改进建议
title: "[FEATURE] <简述功能建议>"
labels: ["enhancement"]
assignees:
  - GEMILUXVII
body:
  - type: markdown
    attributes:
      value: |
        感谢为 CloudRank 插件提出功能建议，请详细描述你的想法

  - type: checkboxes
    id: readme-checked
    attributes:
      label: README 阅读确认
      description: 提交此功能请求前，请确认：
      options:
        - label: 我已阅读项目的 README.md 文档，确认所提功能在现有版本中无法实现，或现有实现存在不足
          required: true

  - type: textarea
    id: problem-related
    attributes:
      label: 此功能请求是否与某个现有问题相关？ (选填)
      description: |
        清晰简洁地描述相关问题如果只是一个新点子，而非解决特定痛点，可简单说明或跳过
        例如：“目前排行榜的发送时间与词云绑定，不够灵活”
        或者：“希望词云有更多预设形状”
      placeholder: "例如：当前 [...] 方面存在不便"

  - type: textarea
    id: solution-description
    attributes:
      label: 描述期望的解决方案或新功能 (必填)
      description: 清晰简洁地描述希望实现的功能及其理想工作方式
      placeholder: |
        例如：“增加配置项，允许独立设置词云的字体字形”
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: 是否考虑过其他替代方案？ (选填)
      description: 清晰简洁地描述在提出此建议前，是否考虑过其他替代方案或类似功能
      placeholder: "例如：曾尝试调整每日词云的 CRON 表达式，但这会同时影响词云生成时间，并非理想方案"

  - type: textarea
    id: additional-context
    attributes:
      label: 补充信息 (选填)
      description: |
        在此添加关于此功能请求的其他上下文、使用场景、预期益处、可能的实现思路（若方便）或相关截图
      placeholder: |
        例如：“此功能有助于群管理员更灵活地管理社群，并及时激励活跃用户”
        （可在此附上相关的草图或参考示例截图）

  - type: markdown
    attributes:
      value: |
        感谢你的建议！
